FROM node:10.16.0-jessie AS builder
WORKDIR /etc/app
ADD . ./
RUN apt-get update && apt-get -y install vim openssh-client && mkdir ssh-key && ssh-keygen -q -t rsa -N '' -f /etc/app/ssh-key/id_rsa && ssh-keygen -f /etc/app/ssh-key/id_rsa.pub -m "PEM" -e > /etc/app/ssh-key/public.pem &&  npm install 
RUN mkdir testdata
CMD npm run test